@startuml

title __INTERFACES's Class Diagram__\n

  namespace  {
    namespace odel {
      namespace Interfaces {
        interface Model.Interfaces.IFlatbed {
            {abstract} + flatbedHasNoAngle()
            {abstract} + getFlatbedAngle()
            {abstract} + getMaxFlatbedAngle()
            {abstract} + lowerFlatbed()
            {abstract} + raiseFlatbed()
            {abstract} + setFlatbedAngle()
        }
      }
    }
  }
  

  namespace  {
    namespace odel {
      namespace Interfaces {
        interface Model.Interfaces.IMovable {
            {abstract} + move()
            {abstract} + turnLeft()
            {abstract} + turnRight()
        }
      }
    }
  }
  

  namespace  {
    namespace odel {
      namespace Interfaces {
        enum Direction {
          EAST
          NORTH
          SOUTH
          WEST
        }
      }
    }
  }
  

  namespace  {
    namespace odel {
      namespace Interfaces {
        interface Model.Interfaces.IPositionable {
            {abstract} + getX()
            {abstract} + getY()
            {abstract} + setX()
            {abstract} + setY()
        }
      }
    }
  }
  

  namespace  {
    namespace odel {
      namespace Interfaces {
        interface Model.Interfaces.IRamp {
            {abstract} + closeRamp()
            {abstract} + isRampOpen()
            {abstract} + openRamp()
            {abstract} + setRampOpen()
        }
      }
    }
  }
  

  namespace  {
    namespace odel {
      namespace Interfaces {
        interface Model.Interfaces.ISizeable {
            {abstract} + getHeight()
            {abstract} + getLength()
            {abstract} + getWidth()
            {abstract} + setHeight()
            {abstract} + setLength()
            {abstract} + setWidth()
        }
      }
    }
  }
  

  namespace  {
    namespace odel {
      namespace Interfaces {
        interface Model.Interfaces.ITransportable {
            {abstract} + isLoaded()
            {abstract} + setLoaded()
        }
      }
    }
  }
  

  namespace  {
    namespace odel {
      namespace Interfaces {
        interface Model.Interfaces.ITransportableHolder {
            {abstract} + dropTransport()
            {abstract} + getLoadedTransport()
            {abstract} + loadTransport()
        }
      }
    }
  }
  

  Model.Interfaces.IMovable +-down- Model.Interfaces.IMovable.Direction


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
